// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBphrCBBCj6clhE-ARRn4CfUvxWwG9NFUQ',
    appId: '1:1040391139063:web:7350baea4547e47d2fadf2',
    messagingSenderId: '1040391139063',
    projectId: 'greenroute-e467c',
    authDomain: 'greenroute-e467c.firebaseapp.com',
    storageBucket: 'greenroute-e467c.appspot.com',
    measurementId: 'G-6B4N9YHGH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZs0CNSfDxSP5zJBLTwjm3uSSnWAWzn8Q',
    appId: '1:1040391139063:android:44fc566469a1cb742fadf2',
    messagingSenderId: '1040391139063',
    projectId: 'greenroute-e467c',
    storageBucket: 'greenroute-e467c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkVNONC3ZkLz1j7WUfEtWrdpc2MpqxjE',
    appId: '1:1040391139063:ios:4246b83b7343c19e2fadf2',
    messagingSenderId: '1040391139063',
    projectId: 'greenroute-e467c',
    storageBucket: 'greenroute-e467c.appspot.com',
    iosBundleId: 'com.example.greenroute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgkVNONC3ZkLz1j7WUfEtWrdpc2MpqxjE',
    appId: '1:1040391139063:ios:4246b83b7343c19e2fadf2',
    messagingSenderId: '1040391139063',
    projectId: 'greenroute-e467c',
    storageBucket: 'greenroute-e467c.appspot.com',
    iosBundleId: 'com.example.greenroute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBphrCBBCj6clhE-ARRn4CfUvxWwG9NFUQ',
    appId: '1:1040391139063:web:adde0b59d87895c42fadf2',
    messagingSenderId: '1040391139063',
    projectId: 'greenroute-e467c',
    authDomain: 'greenroute-e467c.firebaseapp.com',
    storageBucket: 'greenroute-e467c.appspot.com',
    measurementId: 'G-13YE672EW8',
  );
}
